# Generated by Django 4.0.3 on 2022-03-22 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 12, 13, 53, 16265, tzinfo=utc)),
        ),
    ]
